### ISSUE TITLE
Pass Global variables to jq filter

### ISSUE THREAD

**Issue by GameMaster47** [rundeck-plugins/jq-json-logfilter#3]
I'm wondering if it's possible to run the following in jq-filter in order to capture a value in a json output:

.[] |  select( .address | contains (${Variables_Uplink_Update.ipAddress}))

The ${Variables_Uplink_Update.ipAddress} is a Global variable on the jobs.

Best regards!

**Comment by ltamaster** [comment]
this PR should do this
https://github.com/rundeck-plugins/jq-json-logfilter/pull/5
